services:
  postgres:
    image: postgres:latest
    container_name: ${DOCKER_POSTGRES_CONTAINER}
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: